### ISSUE TITLE
How to change the line color?

### ISSUE THREAD

**Issue by gabrieldepaula** [luileito/jsketch#1]
the jquery option

graphics: {
    strokeStyle: '#000',
},

has no effect! he still drawing in #F0F

Just the loaded strokes has change their color.

Can you help me??

**Comment by luileito** [comment]
Do you have a Minimal Working Example? 

If you look at the source code of https://luis.leiva.name/lectures/blackboard/ you'll see how to set background and stroke color.

**Comment by gabrieldepaula** [comment]
Wow! Thanks! worked pretty well! :)

Now I just need to resolve the SVG export that is giving this message to me:

jquery.sketchable.full.min.js:2 Uncaught TypeError: e.sketch.toSVG is not a function
    at k.fn.init.create (jquery.sketchable.full.min.js:2)
    at k.fn.init.a.fn.sketchable (jquery.sketchable.full.min.js:2)
    at HTMLButtonElement.<anonymous> (page.reports.save2.js:36)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

My code:

$(function(){
    var $canvas = $('#signature');

    $canvas.attr({
        'width': 600,
        'height': 300,
    }).css({
        'background-color': "#FFF",
    }).sketchable({
        graphics: {
            strokeStyle: '#000',
        }
    });

    $('form.group-7').on('submit', function(e) {
        contents = $canvas.sketchable('serializer.save');

        var isEmpty = JSON.parse(contents).strokes.length == 0 ? true : false;

        if(isEmpty) {
            $('input[name="signature"]').val('');
        } else {
            $('input[name="signature"]').val(contents);
        }
    });

    if($('input[name="signature"]').val()) {
        $canvas.sketchable('serializer.load', $('input[name="signature"]').val());
    }

    $('.btn-export-signature').on('click', function(e) {
        e.preventDefault();

        $canvas.sketchable('svg.create', function(contents) {
            console.log(contents);
        });
    });
});

Can you help me??

**Comment by luileito** [comment]
Glad it worked. Now you're talking about a different issue, though. Please download the latest files and try again. I tested your example with the following scripts:
```js
  <script type="text/javascript" src="js/vendor/jquery-1.7.2.min.js"></script>
  <script type="text/javascript" src="js/dist/jsketch.min.js"></script>
  <script type="text/javascript" src="js/dist/jquery.sketchable.full.min.js"></script>
```

**Comment by gabrieldepaula** [comment]
Worked! thanks!! 

I think I was using outdated files.
