### ISSUE TITLE
[Support query] Please could you add a basic example for changing the line style?

### ISSUE THREAD

**Issue by Wikinaut** [luileito/jsketch#2]
I use the very basic example but failed to get other line styles working like other colors then magenta and thickness.

```
$(function() {
    var $sketcher = $('#drawing-canvas').sketchable();
});
```

**Comment by luileito** [comment]
Have you tried to set the `graphics` property?
https://luis.leiva.name/jsketch/js/docs/$.fn.sketchable.defaults.html

**Comment by luileito** [comment]
Added new demo at https://luis.leiva.name/jsketch/demo-graphics.php
